/* date = April 18th 2024 1:25 pm */

#ifndef RESOURCE_IDS_H
#define RESOURCE_IDS_H

#define ID_FONT 256
#define ID_SHADER 257
#define IM_FELL_FONT_ID 100
#define VERTEX_SHADER_SOURCE 101
#define FRAGMENT_SHADER_SOURCE 102

#endif //RESOURCE_IDS_H
